#服务器配置
server:
  port: 8081
  context-path: /
spring:
  #MySQL配置
  datasource:
    url: jdbc:mysql://localhost:3306/lanlinker_job_ver2.0
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  #JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  #输出日期格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  #文件上传大小配置
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
#文件上传位置
fileLocation:
  total-path: /usr/LanlinkerDB2
  img-path: /imgDB/
  file-path: /fileDB/
